name: Deploy
on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install step
        run: "npm install && npm i --save-dev @types/express && npm i -S googleapis && npm install --save @types/cors"

      - name: Build step
        run: "tsc"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "irvin-wedding-backend"
          entrypoint: "index.js"
          root: "./dist"
          
          
